#!/usr/bin/env python3
"""One-time builder: writes scripts/_gen_vocab_extra.py with full embedded vocabulary."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCRIPTS = ROOT / "scripts"
OUT = SCRIPTS / "_gen_vocab_extra.py"
CAT_DIR = ROOT / "src" / "data" / "categories"

NUMBER_WORDS = sorted([
    "zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine",
    "ten", "eleven", "twelve", "thirteen", "fourteen", "fifteen", "sixteen",
    "seventeen", "eighteen", "nineteen", "twenty", "thirty", "forty", "fifty",
    "sixty", "seventy", "eighty", "ninety", "hundred", "thousand", "lakh",
    "twenty-one", "twenty-two", "twenty-three", "twenty-four", "twenty-five",
    "twenty-six", "twenty-seven", "twenty-eight", "twenty-nine", "thirty-one",
    "thirty-two", "thirty-five", "forty-five", "two hundred", "five hundred",
])


def load_base(cat: str) -> list[list]:
    p = CAT_DIR / f"{cat}.json"
    data = json.loads(p.read_text(encoding="utf-8"))
    rows = []
    for w in data["words"]:
        rows.append([w["en"], w["bn"], w.get("emoji", ""), w.get("roman", "")])
    return rows


def t(en, bn, emoji="", roman=""):
    return [en, bn, emoji, roman]


# Extra vocabulary beyond src/data/categories (Bangladesh-friendly Bangla)
EXTRAS: dict[str, list[list]] = {}

EXTRAS["animals"] = [
    t("squirrel", "কাঠবিড়াল", "🐿️", "kathbiral"),
    t("hamster", "হ্যামস্টার", "🐹", "hamstar"),
    t("guinea pig", "গিনি পিগ", "🐹", "guini pig"),
    t("otter", "উদবিলাতি", "🦦", "udbilati"),
    t("seal", "সিল", "🦭", "sil"),
    t("walrus", "ওয়ালরাস", "🦭", "walras"),
    t("polar bear", "ধূসর ভালুক", "🐻‍❄️", "dhusor bhaluk"),
    t("panda", "পান্ডা", "🐼", "panda"),
    t("koala", "কোআলা", "🐨", "koala"),
    t("kangaroo", "ক্যাঙ্গারু", "🦘", "kangaru"),
    t("sloth", "আলসে প্রাণী", "🦥", "alše prani"),
    t("hedgehog", "কাঁটাহাড়", "🦔", "kãtahar"),
    t("porcupine", "শজারু", "🦔", "shojaru"),
    t("skunk", "গন্ধগোকুল", "🦨", "gondhogokul"),
    t("raccoon", "র‍্যাকুন", "🦝", "rækun"),
    t("bat", "বাদুড়", "🦇", "badur"),
    t("mole", "ছুচো", "🐀", "chucho"),
    t("beaver", "বিভার", "🦫", "bivar"),
    t("moose", "মুস", "🫎", "mus"),
    t("reindeer", "রেইনডিয়ার", "🦌", "reindear"),
    t("bison", "বাইসন", "🦬", "bison"),
    t("yak", "ইয়াক", "🐂", "yak"),
    t("ox", "বলদ", "🐂", "bolod"),
    t("donkey", "গাধা", "🫏", "gadha"),
    t("mule", "খচ্চর", "🫏", "khachchor"),
    t("pony", "শিশু ঘোড়া", "🐴", "shishu ghora"),
    t("rhinoceros", "গন্ডার", "🦏", "gondar"),
    t("hippopotamus", "জলহস্তী", "🦛", "jolhasti"),
    t("cheetah", "চিতা বাঘ", "🐆", "chita bagh"),
    t("leopard", "চিতা", "🐆", "chita"),
    t("jaguar", "জাগুয়ার", "🐆", "jaguar"),
    t("panther", "কালো বাঘ", "🐆", "kalo bagh"),
    t("hyena", "হায়না", "🐕", "hayna"),
    t("mongoose", "বেঙ্গল", "🐾", "bengol"),
    t("meerkat", "মিরক্যাট", "🐾", "mirkat"),
    t("armadillo", "আর্মাডিলো", "🐾", "armadilo"),
    t("tapir", "টেপির", "🐾", "tepir"),
    t("llama", "লামা", "🦙", "lama"),
    t("alpaca", "আলপাকা", "🦙", "alpaka"),
    t("ostrich", "অস্ট্রিচ", "🦃", "ostrich"),
    t("emu", "ইমু", "🦃", "imu"),
    t("flamingo", "ফ্ল্যামিঙ্গো", "🦩", "flamingo"),
    t("pelican", "পেলিকান", "🦢", "pelikan"),
    t("swan", "রাজহাঁস", "🦢", "rajhans"),
    t("turkey", "তুরকি", "🦃", "turki"),
    t("eagle", "ঈগল", "🦅", "ishor"),
    t("hawk", "বাজ", "🦅", "baj"),
    t("woodpecker", "কাঠঠোকরা", "🪶", "kaththokra"),
    t("kingfisher", "মাছরাঙা", "🐦", "machranga"),
    t("heron", "বক", "🦢", "bok"),
    t("stork", "সারস", "🦩", "sars"),
    t("seagull", "সীগাল", "🕊️", "sigal"),
    t("hummingbird", "হামিংবার্ড", "🐦", "hummingbird"),
    t("canary", "ক্যানারি", "🐦", "kanari"),
    t("finch", "ফিঞ্চ", "🐦", "finch"),
    t("myna", "শালিক", "🐦", "shalik"),
    t("cuckoo", "কোকিল", "🐦", "kokil"),
    t("magpie", "কোঁকড়া", "🐦", "kõkra"),
    t("raven", "ডাকপাখি", "🐦‍⬛", "dakpakhi"),
    t("dove", "ঘুঘু", "🕊️", "ghughu"),
    t("quail", "তিতির", "🐦", "titir"),
    t("pheasant", "মাঝপাখি", "🐦", "majhpakhi"),
    t("cockatoo", "কাকাতু", "🦜", "kakatu"),
    t("macaw", "ম্যাকaw", "🦜", "makaw"),
    t("toucan", "টুকান", "🦜", "tukan"),
    t("weaver bird", "বাবুই", "🐦", "babui"),
    t("hornbill", "ধনেশ", "🐦", "dhanesh"),
    t("drongo", "ফিঙ্গে", "🐦", "phinge"),
    t("kite bird", "চিল", "🦅", "chil"),
    t("duckling", "হাঁসের বাচ্চা", "🐤", "hasher baccha"),
    t("shark", "হাঙ্গর", "🦈", "hangor"),
    t("octopus", "অক্টোপাস", "🐙", "octopus"),
    t("squid", "স্কuid", "🦑", "skuid"),
    t("jellyfish", "জেলিফিশ", "🪼", "jelifish"),
    t("starfish", "তaramachh", "⭐", "taramachh"),
    t("seahorse", "ঘোড়ামাছ", "🐴", "ghoramachh"),
    t("lobster", "লবস্টার", "🦞", "lobstar"),
    t("oyster", "ঝিনুক", "🦪", "jhinuk"),
    t("clam", "শামুক", "🐚", "shamuk"),
    t("eel", "কুচিয়া", "🐍", "kuchia"),
    t("stingray", "শঙkuch", "🐟", "shonkuch"),
    t("goldfish", "সোনামাছ", "🐠", "sonamachh"),
    t("catfish", "মagur", "🐟", "magur"),
    t("hilsa fish", "ইlish", "🐟", "ilish"),
    t("rohu fish", "রui", "🐟", "rui"),
    t("katla fish", "কatla", "🐟", "katla"),
    t("tuna", "টুনা", "🐟", "tuna"),
    t("salmon", "সalmon", "🐟", "salmon"),
    t("orca", "অর্কা", "🐋", "orka"),
    t("lizard", "টিকটiki", "🦎", "tiktiki"),
    t("gecko", "টিকটiki", "🦎", "tiktiki"),
    t("chameleon", "বহুরূপী", "🦎", "bohurupi"),
    t("python snake", "ajgar", "🐍", "ajgar"),
    t("cobra snake", "cobra", "🐍", "kobra"),
    t("toad", "বeng", "🐸", "beng"),
    t("beetle", "পোকা", "🪲", "poka"),
    t("dragonfly", "dragonfly", "🪰", "dragonfly"),
    t("grasshopper", "ঘাসফড়ing", "🦗", "ghasforing"),
    t("cricket insect", "ঝিঁঝিঁ", "🦗", "jhinjhin"),
    t("cockroach", "তelapoka", "🪳", "telapoka"),
    t("moth", "moth", "🦋", "moth"),
    t("caterpillar", "caterpillar", "🐛", "caterpillar"),
    t("worm", "কrmo", "🪱", "krmo"),
    t("snail", "snail", "🐌", "shamuk"),
    t("scorpion", "scorpion", "🦂", "birkosh"),
    t("ladybug", "ladybug", "🐞", "ledibag"),
    t("firefly", "firefly", "✨", "jonaki"),
    t("wasp", "wasp", "🐝", "bhoral"),
    t("hornet", "hornet", "🐝", "bhoral"),
    t("calf", "বাছুর", "🐄", "bachhur"),
    t("lamb", "বাছা", "🐑", "bachha"),
    t("kid goat", "ছাগলছানা", "🐐", "chagolchhana"),
    t("piglet", "শূকরছানা", "🐷", "shukorchhana"),
    t("foal", "ঘোড়াছানা", "🐴", "ghorachhana"),
    t("fawn", "হরin chhana", "🦌", "horin chhana"),
    t("bear cub", "ভালুকছানা", "🐻", "bhaluk chhana"),
    t("kitten", "বিড়al chhana", "🐱", "biṛal chhana"),
    t("tadpole", "tadpole", "🐸", "tadpole"),
    t("silkworm", "resham poka", "🐛", "resham poka"),
    t("earthworm", "krmo", "🪱", "krmo"),
    t("leech", "jok", "🪱", "jok"),
    t("sea lion", "sea lion", "🦭", "si layon"),
    t("platypus", "platypus", "🦆", "platipus"),
    t("lemur", "lemur", "🐒", "lemur"),
    t("gibbon", "gibbon", "🐒", "gibbon"),
    t("orangutan", "orangutan", "🦧", "orangutan"),
    t("chimpanzee", "chimpanzee", "🐒", "chimpanji"),
    t("gorilla", "gorilla", "🦍", "gorila"),
    t("baboon", "baboon", "🐒", "babun"),
    t("pangolin", "বonrui", "🐾", "bonrui"),
    t("anteater", "পিঁপড়া ভক্ষক", "🐾", "pipra bhokkhok"),
    t("ferret", "ফerret", "🐾", "feret"),
    t("weasel", "বnashpoti", "🐾", "banshpoti"),
    t("badger", "বajer", "🐾", "bajer"),
    t("snow leopard", "হিম বাঘ", "🐆", "him bagh"),
    t("wild boar", "বন শূকর", "🐗", "bon shukor"),
    t("boar", "শূকর", "🐗", "shukor"),
    t("ram", "পুরুষ ভেড়া", "🐏", "purush bhera"),
    t("ewe", "মাদা ভেড়া", "🐑", "mada bhera"),
    t("bull", "ষাঁড়", "🐂", "shãṛ"),
    t("heifer", "বকনা", "🐄", "bokna"),
    t("stallion", "ঘোড়া", "🐴", "ghora"),
    t("mare", "মাদা ঘোড়া", "🐴", "mada ghora"),
    t("robin bird", "রবin", "🐦", "robin"),
    t("nightingale", "bulbuli", "🐦", "bulbuli"),
    t("lovebird", "prem pakhi", "🐦", "prem pakhi"),
    t("parakeet", "tiya pakhi", "🦜", "tiya pakhi"),
    t("blue jay", "nil kak", "🐦", "nil kak"),
    t("wren", "titti", "🐦", "titti"),
    t("thrush", "doel", "🐦", "doel"),
    t("barbet bird", "basantaraj", "🐦", "basantaraj"),
    t("roller bird", "nilkantho", "🐦", "nilkantho"),
    t("sunbird", "moutusi", "🐦", "moutusi"),
    t("sandpiper", "bela pakhi", "🐦", "bela pakhi"),
    t("tern bird", "samudrik pakhi", "🐦", "samudrik pakhi"),
    t("cormorant", "pankowri", "🐦", "pankowri"),
    t("sand crab", "kakra", "🦀", "kakra"),
    t("hermit crab", "hermit kakra", "🦀", "hermit kakra"),
    t("porpoise", "porpoise", "🐬", "porpois"),
    t("manatee", "manatee", "🐋", "manati"),
    t("beluga whale", "beluga timi", "🐋", "beluga timi"),
    t("blue whale", "nil timi", "🐋", "nil timi"),
    t("swordfish", "toyar machh", "🐟", "toyar machh"),
    t("marlin", "marlin machh", "🐟", "marlin machh"),
    t("trout", "trout machh", "🐟", "trout machh"),
    t("carp", "karp machh", "🐟", "karp machh"),
    t("pomfret", "pomfret machh", "🐟", "pomfret machh"),
    t("sardine", "sardine machh", "🐟", "sardine machh"),
    t("mackerel", "mackerel machh", "🐟", "mackerel machh"),
    t("pufferfish", "fufo machh", "🐡", "fufo machh"),
    t("clownfish", "klown machh", "🐠", "klown machh"),
    t("alligator", "alligator", "🐊", "alligator"),
    t("iguana", "iguana", "🦎", "iguana"),
    t("salamander", "salamander", "🦎", "salamander"),
    t("centipede", "shatopadi", "🐛", "shatopadi"),
    t("millipede", "hajar padi", "🐛", "hajar padi"),
    t("flea", "upad", "🦟", "upad"),
    t("tick insect", "tik", "🪲", "tik"),
    t("cicada", "sikada", "🦗", "sikada"),
    t("termite", "uistachor", "🐜", "uistachor"),
    t("bumblebee", "bambelbi", "🐝", "bambelbi"),
    t("colt", "ghorachhana", "🐴", "ghorachhana"),
    t("pup", "kukurchhana", "🐶", "kukurchhana"),
    t("wolf cub", "nekre chhana", "🐺", "nekre chhana"),
    t("lion cub", "singho chhana", "🦁", "singho chhana"),
    t("tiger cub", "bagh chhana", "🐯", "bagh chhana"),
    t("elephant calf", "hati chhana", "🐘", "hati chhana"),
    t("monkey baby", "banor chhana", "🐵", "banor chhana"),
    t("rabbit kit", "khorgosh chhana", "🐰", "khorgosh chhana"),
    t("seal pup", "sil chhana", "🦭", "sil chhana"),
    t("cygnet", "rajhanser baccha", "🦢", "rajhanser baccha"),
    t("gosling", "hash chhana", "🐤", "hash chhana"),
    t("penguin chick", "penguin chhana", "🐧", "penguin chhana"),
    t("owl chick", "pecha chhana", "🦉", "pecha chhana"),
    t("eaglet", "ishor chhana", "🦅", "ishor chhana"),
    t("nestling", "ghare bachcha", "🐦", "ghare bachcha"),
    t("hatchling", "dim theke bachcha", "🐣", "dim theke bachcha"),
    t("school of fish", "machher jhund", "🐟", "machher jhund"),
    t("flock of birds", "pakhir jhund", "🐦", "pakhir jhund"),
    t("herd of cows", "gorur jhund", "🐄", "gorur jhund"),
    t("pack of wolves", "nekrer dal", "🐺", "nekrer dal"),
    t("pride of lions", "singher dal", "🦁", "singher dal"),
    t("colony of ants", "piprer koloni", "🐜", "piprer koloni"),
    t("swarm of bees", "moumachir jhund", "🐝", "moumachir jhund"),
]

print("extras animals", len(EXTRAS["animals"]))
