"""High-confidence Bangla fixes applied on top of base + extras."""

QUALITY_OVERRIDES: dict[str, str] = {
    # home (git HEAD base corruption)
    "home|comb": "আঁচা",
    "home|humidifier": "আর্দ্রতা বৃদ্ধিকারী",
    "home|dehumidifier": "আর্দ্রতা কমানো যন্ত্র",
    "home|hanger": "কাপড় ঝুলানোর হ্যাঙার",
    # body
    "body|pinky finger": "ছোট আঙুল",
    "body|little toe": "ছোট আঙুল",
    "body|eyelid": "চোখের পাত",
    "body|pupil": "চোখের মণি",
    "body|iris": "আইরিস",
    "body|earlobe": "কানের লত",
    "body|eardrum": "কানের পর্দা",
    "body|nostril": "নাকের ফুটো",
    "body|gum": "মাড়ি",
    "body|wisdom tooth": "পাড় দাঁত",
    "body|baby tooth": "দুধ দাঁত",
    "body|uvula": "গলবিল",
    "body|adam apple": "কণ্ঠনাল",
    "body|liver": "যকৃত",
    "body|pancreas": "অগ্ন্যাশয়",
    "body|kidney": "কিডনি",
    "body|phlegm": "বেলগাম",
    "body|thought": "চিন্তা",
    "body|strength": "শক্তি",
    "body|energy": "শক্তি",
    "body|growth": "বৃদ্ধি",
    "body|height growth": "উচ্চতা",
    "body|weight": "ওজন",
    "body|expression": "অভিব্যক্তি",
    "body|body language": "দেহের ভাষা",
    "body|fitness": "শারীরিক সুস্থতা",
    "body|instinct": "সহজাত প্রবৃত্তি",
    "body|immune system": "রোগ প্রতিরোধ ক্ষমতা",
    "body|smell sense": "গন্ধ",
    "body|reflex": "স্বাভাবিক প্রতিক্রিয়া",
    # clothes
    "clothes|crossbody bag": "কাঁধের ব্যাগ",
    "clothes|handbag": "হ্যান্ডব্যাগ",
    "clothes|wallet": "ওয়ালেট",
    "clothes|coin purse": "কয়েন ব্যাগ",
    "clothes|keychain": "চাবির রিং",
    "clothes|bathrobe": "গোসলের গাউন",
    "clothes|earmuffs": "কানের কভার",
    "clothes|swimsuit": "সাঁতারের পোশাক",
    # feelings
    "feelings|depressed": "বিষণ্ণ",
}
