"""Curated transport extras — native-quality Bangla, toddler-friendly."""

TRANSPORT_EXTRAS: list[tuple[str, str, str, str]] = [
    ("auto rickshaw", "অটো রিকশা", "🛺", "auto rickshaw"),
    ("cycle rickshaw", "সাইকেল রিকশা", "🚲", "cycle rickshaw"),
    ("tempo", "টেম্পো", "🛺", "tempo"),
    ("microbus", "মাইক্রোবাস", "🚐", "microbus"),
    ("minibus", "মিনিবাস", "🚌", "minibus"),
    ("double decker", "দোতলা বাস", "🚌", "double decker"),
    ("school bus", "স্কুল বাস", "🚌", "school bus"),
    ("express train", "এক্সপ্রেস ট্রেন", "🚆", "express train"),
    ("local train", "লোকাল ট্রেন", "🚆", "local train"),
    ("metro rail", "মেট্রো রেল", "🚇", "metro rail"),
    ("monorail", "মোনোরেল", "🚝", "monorail"),
    ("cargo ship", "মালবাহী জাহাজ", "🚢", "cargo ship"),
    ("fishing boat", "মাছ ধরার নৌকা", "⛵", "mach dharar nouka"),
    ("speedboat", "স্পিডবোট", "🚤", "speedboat"),
    ("yacht", "ইয়ট", "⛵", "yacht"),
    ("canoe", "ডিঙি", "🛶", "canoe"),
    ("kayak", "কায়াক", "🛶", "kayak"),
    ("raft", "ভেলা", "🛶", "raft"),
    ("paddle boat", "প্যাডেল নৌকা", "🛶", "paddle boat"),
    ("water taxi", "জল ট্যাক্সি", "🚤", "water taxi"),
    ("launch", "লঞ্চ", "🚢", "launch"),
    ("hovercraft", "হোভারক্রাফট", "🚤", "hovercraft"),
    ("glider", "গ্লাইডার", "🛩️", "glider"),
    ("hot air balloon", "গরম বাতাসের বেলুন", "🎈", "gorom bataser belun"),
    ("parachute", "প্যারাসুট", "🪂", "parachute"),
    ("skateboard", "স্কেটবোর্ড", "🛹", "skateboard"),
    ("roller skates", "রোলার স্কেট", "🛼", "roller skates"),
    ("segway", "সেগওয়ে", "🛴", "segway"),
    ("unicycle", "একচাকা সাইকেল", "🚲", "ekchaka cycle"),
    ("tricycle", "তিনচাকা সাইকেল", "🚲", "tinchaka cycle"),
    ("handcart", "হাতঠেলা গাড়ি", "🛒", "hath thela gari"),
    ("bullock cart", "গরু গাড়ি", "🐂", "goru gari"),
    ("horse carriage", "ঘোড়া গাড়ি", "🐴", "ghora gari"),
    ("palanquin", "পালকি", "🛏️", "palki"),
    ("sedan", "সেডান", "🚗", "sedan"),
    ("hatchback", "হ্যাচব্যাক", "🚗", "hatchback"),
    ("suv", "এসইউভি", "🚙", "suv"),
    ("pickup truck", "পিকআপ ট্রাক", "🛻", "pickup truck"),
    ("dump truck", "ডাম্প ট্রাক", "🚚", "dump truck"),
    ("tow truck", "টো ট্রাক", "🚛", "tow truck"),
    ("garbage truck", "আবর্জনা ট্রাক", "🚛", "garbage truck"),
    ("cement mixer", "সিমেন্ট মিক্সার", "🚛", "cement mixer"),
    ("crane truck", "ক্রেন", "🏗️", "crane"),
    ("bulldozer", "বুলডোজার", "🚜", "bulldozer"),
    ("excavator", "এক্সকাভেটর", "🚜", "excavator"),
    ("forklift", "ফর্কলিফট", "🏗️", "forklift"),
    ("golf cart", "গলফ কার্ট", "⛳", "golf cart"),
    ("snowmobile", "স্নোমোবাইল", "🛷", "snowmobile"),
    ("sled", "স্লেজ", "🛷", "sled"),
    ("wheelchair", "হুইলচেয়ার", "♿", "wheelchair"),
    ("stroller", "শিশু গাড়ি", "👶", "shishu gari"),
    ("shopping cart", "কেনাকাটার ঠেলা গাড়ি", "🛒", "kenakatar thela gari"),
    ("luggage cart", "মালপত্রের ঠেলা গাড়ি", "🧳", "luggage cart"),
    ("trolley", "ট্রলি", "🛒", "trolley"),
    ("escalator", "এসকেলেটর", "🛗", "escalator"),
    ("elevator", "লিফট", "🛗", "lift"),
    ("moving walkway", "চলন্ত ফুটপাথ", "🚶", "moving walkway"),
    ("highway", "মহাসড়ক", "🛣️", "mahasarak"),
    ("expressway", "এক্সপ্রেসওয়ে", "🛣️", "expressway"),
    ("alley", "গলি", "🛣️", "goli"),
    ("path", "পথ", "🛤️", "poth"),
    ("sidewalk", "ফুটপাথ", "🚶", "footpath"),
    ("crosswalk", "জেব্রা ক্রসিং", "🚸", "crosswalk"),
    ("roundabout", "গোলচক্কর", "🔄", "roundabout"),
    ("intersection", "চৌমাথা", "✖️", "choumatha"),
    ("tunnel", "টানেল", "🚇", "tunnel"),
    ("overpass", "ওভারপাস", "🛣️", "overpass"),
    ("underpass", "আন্ডারপাস", "🛣️", "underpass"),
    ("parking lot", "পার্কিং", "🅿️", "parking"),
    ("garage parking", "গ্যারেজ", "🅿️", "garage"),
    ("gas station", "পেট্রল পাম্প", "⛽", "petrol pump"),
    ("charging station", "চার্জিং স্টেশন", "🔌", "charging station"),
    ("toll booth", "টোল বুথ", "💰", "toll booth"),
    ("weigh station", "ওজন কেন্দ্র", "⚖️", "weigh station"),
    ("border crossing", "সীমান্ত পার", "🛃", "border crossing"),
    ("customs", "শুল্ক", "🛃", "customs"),
    ("port", "বন্দর", "⚓", "bandar"),
    ("harbor", "বন্দর", "⚓", "bandar"),
    ("dock", "ঘাট", "⚓", "ghat"),
    ("pier", "ঘাট", "🌊", "ghat"),
    ("runway", "রানওয়ে", "🛫", "runway"),
    ("control tower", "নিয়ন্ত্রণ টাওয়ার", "🗼", "control tower"),
    ("hangar", "হ্যাংগার", "🛩️", "hangar"),
    ("helipad", "হেলিপ্যাড", "🚁", "helipad"),
    ("train track", "রেল লাইন", "🛤️", "rail line"),
    ("railway crossing", "রেলগেট", "🚧", "railgate"),
    ("platform", "প্ল্যাটফর্ম", "🚉", "platform"),
    ("waiting room", "অপেক্ষাকক্ষ", "🪑", "opekkakakkho"),
    ("departure", "ছাড়ার সময়", "🛫", "chharar somoy"),
    ("arrival", "আগমন", "🛬", "agomon"),
    ("boarding pass", "বোর্ডিং পাস", "🎫", "boarding pass"),
    ("passport", "পাসপোর্ট", "🛂", "passport"),
    ("visa", "ভিসা", "🛂", "visa"),
    ("luggage", "ভ্রমণ ব্যাগ", "🧳", "travel bag"),
    ("suitcase", "স্যুটকেস", "🧳", "suitcase"),
    ("backpack travel", "ভ্রমণ ব্যাগ", "🎒", "travel bag"),
    ("duffel bag", "ডাফেল ব্যাগ", "🧳", "duffel bag"),
    ("seat belt", "সিট বেল্ট", "💺", "seat belt"),
    ("car seat", "গাড়ির সিট", "💺", "car seat"),
    ("dashboard", "ড্যাশবোর্ড", "🚗", "dashboard"),
    ("rearview mirror", "পেছনের আয়না", "🪞", "rearview mirror"),
    ("windshield", "উইন্ডশিল্ড", "🚗", "windshield"),
    ("wiper", "ওয়াইপার", "🌧️", "wiper"),
    ("headlight", "হেডলাইট", "💡", "headlight"),
    ("taillight", "টেললাইট", "🔴", "taillight"),
    ("turn signal", "টার্ন সিগন্যাল", "↔️", "turn signal"),
    ("speedometer", "স্পিডোমিটার", "🏎️", "speedometer"),
    ("odometer", "ওডোমিটার", "📊", "odometer"),
    ("gps", "জিপিএস", "🗺️", "gps"),
    ("compass", "কম্পাস", "🧭", "compass"),
    ("life jacket", "জীবনঝাঁকটি", "🦺", "jibon jhakti"),
    ("anchor", "নোঙ্গর", "⚓", "nongor"),
    ("sail", "পাল", "⛵", "pal"),
    ("paddle", "দাঁড়", "🛶", "dar"),
    ("oar", "দাঁড়", "🛶", "dar"),
    ("motor", "মোটর", "⚙️", "motor"),
    ("engine", "ইঞ্জিন", "⚙️", "engine"),
    ("propeller", "প্রোপেলার", "🌀", "propeller"),
    ("jet engine", "জেট ইঞ্জিন", "✈️", "jet engine"),
    ("rocket engine", "রকেট ইঞ্জিন", "🚀", "rocket engine"),
    ("paraglider", "প্যারাগ্লাইডার", "🪂", "paraglider"),
    ("hang glider", "হ্যাং গ্লাইডার", "🪂", "hang glider"),
    ("zip line", "জিপ লাইন", "🪂", "zip line"),
    ("cable car", "কেবল কার", "🚡", "cable car"),
    ("funicular", "ফুনিকুলার", "🚞", "funicular"),
    ("gondola lift", "গন্ডোলা", "🚡", "gondola"),
    ("rickshaw stand", "রিকশা স্ট্যান্ড", "🛺", "rickshaw stand"),
    ("bus stop", "বাস স্টপ", "🚏", "bus stop"),
    ("taxi stand", "ট্যাক্সি স্ট্যান্ড", "🚕", "taxi stand"),
    ("bike lane", "সাইকেল লেন", "🚲", "bike lane"),
    ("traffic jam", "জ্যাম", "🚗", "jam"),
    ("road work", "রাস্তার কাজ", "🚧", "road work"),
    ("detour", "বিকল্প পথ", "↪️", "detour"),
    ("one way", "একমুখী রাস্তা", "➡️", "one way"),
    ("speed limit", "গতিসীমা", "🏎️", "goti sima"),
    ("stop sign", "থামার চিহ্ন", "🛑", "stop sign"),
    ("yield sign", "সাবধান চিহ্ন", "⚠️", "yield sign"),
    ("pedestrian", "পথচারী", "🚶", "pathachari"),
    ("cyclist", "সাইকেল চালক", "🚴", "cycle chalok"),
    ("motorcyclist", "মোটরসাইকেল চালক", "🏍️", "motorcycle chalok"),
    ("dolly", "ঠেলা গাড়ি", "📦", "thela gari"),
    ("conveyor belt", "কনভেয়র বেল্ট", "🏭", "conveyor belt"),
]
